### PR TITLE
MUS-156:LauncherIconChanged

### PR DESCRIPTION
**Pull request by UtpalKumarJha**
Images placed in mipmap from studio 1.1

### CODE REVIEW

**Comment by bteufl** [comment]
The icon is cut off - isn't it? And we don't just want to change the icon on the splash-screen, but also the icon which is always on the right upper corner - have you also done this?

**Comment by UtpalKumarJha** [comment]
It should be good now . Yes i have changed every instance of Launcher Icon.

**Comment by bteufl** [comment]
I googled a little bit about the mipmap-folder. It is useable since android version 4.2 - right?

**Comment by UtpalKumarJha** [comment]
Right .

**Comment by bteufl** [comment]
That's a problem because we have a min-sdk of 15 is it also running on this?

**Comment by UtpalKumarJha** [comment]
Yes .

**Pull request merged**
